
include: "rules/common.smk"
include: "rules/align.smk"
include: "rules/moddotplot.smk"
include: "rules/modkit.smk"
include: "rules/nucflag.smk"
include: "rules/svbyeye.smk"

rule all:
    input:
        rules.nucflag_all.input,
        rules.align_all.input,
        rules.moddotplot_all.input,
        rules.svbyeye_all.input,
    default_target:
        True
